
task:
  name: "Lain-Kernel-Builder"
  timeout_in: 2h
  container:
      image: ghcr.io/neutron-toolchains/docker-image:arch-neutron
      cpu: 4
      memory: 8G

  Build_script:
      - ln -fs /usr/share/zoneinfo/Asia/Dhaka /etc/localtime && date
      - locale-gen en_US en_US.UTF-8
      - bash work.sh
